name: UI Component Request
description: Request a new UI component or modification
title: "[Component] <Component Name>"
labels: ["ui", "frontend"]
assignees: []

body:
  - type: markdown
    attributes:
      value: "### UI Component Request"

  - type: input
    id: component-name
    attributes:
      label: "Component Name"
      placeholder: "Search Bar, Sidebar Menu, etc."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the purpose of this component and where it will be used."
    validations:
      required: true

  - type: textarea
    id: design-mockup
    attributes:
      label: "Design Mockups or References"
      description: "Attach Figma links, screenshots, or any visual reference."

  - type: textarea
    id: props
    attributes:
      label: "Component Props"
      description: "List down any props (e.g., `placeholder`, `onClick`, `disabled`)."

  - type: textarea
    id: behavior
    attributes:
      label: "Expected Behavior"
      description: "Describe how this component should behave."

  - type: textarea
    id: dependencies
    attributes:
      label: "Dependencies"
      description: "Any libraries or existing components it relies on."

  - type: dropdown
    id: priority
    attributes:
      label: "Priority Level"
      options:
        - "High"
        - "Medium"
        - "Low"
    validations:
      required: true
