name: Constant Object Definition
description: Define a new constant object or modify an existing one
title: "[Constant] <Constant Name>"
labels: ["constants", "data-structure"]
assignees: []

body:
  - type: markdown
    attributes:
      value: "### Constant Object Definition"

  - type: input
    id: constant-name
    attributes:
      label: "Constant Name"
      placeholder: "Example: ROUTE_TYPE, ERROR_CODES"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Explain what this constant is for and how it will be used."
    validations:
      required: true

  - type: textarea
    id: structure
    attributes:
      label: "Object Structure"
      description: "Provide a sample structure of the constant."
      placeholder: |
        {
          "key1": "value1",
          "key2": "value2"
        }
    validations:
      required: true

  - type: textarea
    id: usage
    attributes:
      label: "Usage Examples"
      description: "How should this constant be used in the project?"
      placeholder: "Example: Used in API responses or UI dropdowns."

  - type: textarea
    id: dependencies
    attributes:
      label: "Dependencies"
      description: "Does this constant depend on any other constants, APIs, or enums?"

  - type: dropdown
    id: priority
    attributes:
      label: "Priority Level"
      options:
        - "High"
        - "Medium"
        - "Low"
    validations:
      required: true
